#  DISCLAIMER:
# THIS CODE IS SAMPLE CODE. THESE SAMPLES ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND.
# MICROSOFT FURTHER DISCLAIMS ALL IMPLIED WARRANTIES INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTIES OF MERCHANTABILITY OR OF FITNESS FOR
# A PARTICULAR PURPOSE. THE ENTIRE RISK ARISING OUT OF THE USE OR PERFORMANCE OF THE SAMPLES REMAINS WITH YOU. IN NO EVENT SHALL
# MICROSOFT OR ITS SUPPLIERS BE LIABLE FOR ANY DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS,
# BUSINESS INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR OTHER PECUNIARY LOSS) ARISING OUT OF THE USE OF OR INABILITY TO USE THE
# SAMPLES, EVEN IF MICROSOFT HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. BECAUSE SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION
# OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU.

<#
$RemoveNEWGrouptSMTP = Import-Csv distributiongroups.csv
$RemoveNEWGrouptSMTP | % {Set-DistributionGroup -Identity $_.PrimarySmtpAddress -EmailAddresses @{remove=$_.NEWPrimarySmtpAddress} -ErrorAction SilentlyContinue}

#>

$RemoveNEWGroupSMTPAddresses = Import-Csv distributiongroups.csv
 
foreach ($RemoveNEWGroupSMTPAddress in $RemoveNEWGroupSMTPAddresses) {  
    $DGName = $RemoveNEWGroupSMTPAddress.Name
    
    # Get the name of the new primary SMTP address that was assigned
     $NewPrimarySMTP = $RemoveNEWGroupSMTPAddress.NEWPrimarySmtpAddress

    write-host "Removing Primary SMTP Address for:" $DGName -ForegroundColor Green
    $_.NEWPrimarySmtpAddress
    Set-DistributionGroup -Identity $RemoveNEWGroupSMTPAddress.PrimarySmtpAddress -EmailAddresses @{remove=$NewPrimarySMTP} -ErrorAction SilentlyContinue
}


